# question 1
# create simulation 
# set seed 
set.seed(10000)

# set time variable as 0 for loop 
time = 0

# patient vector to get the # of patients and arrival time
Patient = vector()

# add arrival time to patient vector. Arrival time would be randomly generated by using exponential distribution 
while(time < 420){
  dummy <- rexp(1, 1/20)
  time = time + dummy[1]
  Patient <- append(Patient, time)
}

# use floor function to get exact time 
Patient <- floor(Patient)

# if the last element of Patient vector is bigger than 420, remove it because the clinic closes at 4pm. 
if(Patient[length(Patient)] > 420){
  Patient <- Patient[-length(Patient)]
}


# each patient's doctor time 
Doctime <- runif(length(Patient),5,20)

# remove decimal 
Doctime <- floor(Doctime)

# set an empty vector for each patient's waiting time 
waiting <- vector()

# set closing time as 0
closetime = 0

# get waiting time by using loop
# start from 2. The first patient does not have waiting time
# totaltime is the previous patient's arrival time + the time doctor spent
# if the previous patient totaltime is bigger than current arrival time, there's waiting time. Add each waiting time to waiting time vector 
# if there's waiting time, patient arrival time + waiting time to calculate waiting time for next patient 
# at the last get the last patient's finished time 
for (i in 2:length(Doctime)) {
  #totaltime <- 0
  totaltime = Patient[i-1] + Doctime[i-1]
  if(totaltime > Patient[i]){
    waiting <- append(waiting, totaltime- Patient[i])
    Patient[i] <- Patient [i] + (totaltime - Patient[i])
  }
  if(i == length(Patient)){
    closetime = Patient[i] + Doctime[i]
  }
}


# (a)
# the number of patient 
length(Patient)

# (b)
length(waiting)

# (c)
mean(waiting)

# (d)
# get hour and minites from closetime 
hour<- floor(closetime / 60)

# calculate closing time. If closetime is smaller than 420, the office closes at 4. 
# if closetime / 60 < 7, it means that the last patient finished his/her doctor time before 4. 
if(hour < 7){
  minites = closetime - hour*60
  hour <- 9 + hour
  if(hour>12){
    hour <- hour - 12
  }
  cat("The last patient finished at ", hour, ":", minites, ", so the office closed at 4:00pm")
}else{
  hour <- 9 + hour
  if(hour>12){
    hour <- hour - 12
  }
  minites <- closetime - 420
  cat("The office closed at ", hour, ":", minites)
}



# question 2
# (a)
ID<- c(1:12)
Sex <- c(0,0,0,0,0,0,1,1,1,1,1,1)
Treatment <- c(0,1,0,1,0,1,0,1,0,1,0,1)
T.1 <- c(94,46,40,64,6,30,47,36,92,1,32,25)
T.2 <- c(23,92,65,15,34,37,85,41,60,100,66,43)
T.3 <- c(61,97,43,8,59,10,88,3,95,47,62,93)

# scan 
ID <- scan()
Sex <- scan()
Treatment <- scan()
T.1 <- scan()
T.2 <- scan()
T.3 <- scan()
# create a data frame 
data <- data.frame(ID, Sex, Treatment, T.1, T.2, T.3)

# second  way
# I made txt file. 
data2 <- read.table("homeworkdata.txt", header = TRUE, sep = " ")


# (b)
longer <- reshape(data, varying = c("T.1", "T.2", "T.3"), direction = "long", timevar = "followup", v.names= "outcome")

# (c)
# convert sex and treatment to a factor 
longer$Sex <- factor(longer$Sex, levels = c(0,1), labels = c("Male", "Female"))
longer$Treatment <- factor(longer$Treatment)
str(longer)

# create a plot 
library(lattice)
xyplot(outcome~followup | Sex,
data = longer, 
group = Treatment,
col = c("red", "blue"),
pch = c(12,9),
xlim = c(0:4),
xlab = "followup visit", ylab = "outcome",
key = list(text = list(c("Treatment 0", "Treatment 1")),
points = list(pch=c(12,9), col = c("red", "blue")), columns = 1)
)

# question 3
# (a)
library(MASS)
?survey

mean(survey$pulse)

# There are some missing values, so mean does not work. 
str(survey)

# (b)
?mean()
# need to remove NAs
mean(survey$Pulse,na.rm = TRUE)

# (c)
survey$Age <- floor(survey$Age)

# (d)
# create subset for under 20
Under20<-subset(survey, Age<20)
mean(Under20$Pulse, na.rm=TRUE)

# (e)
# create a subset for right handed
Right <- subset(survey, W.Hnd == "Right")
mean(Right$Age, na.rm= TRUE)

# (f)
# create a subset 
Left <- subset(survey, W.Hnd == "Left" & Clap != "Left")
proportion <- nrow(Left) / nrow(survey)

# (g)
plot(log(survey$Age-10), survey$Pulse, xlab = "Log Age - 10", ylab = "Pulse",
pch = 15)


# question 4
# a
# read excel files
# I changed xls to csv 
followup <- read.table("follow.up.csv", sep = ",", header = TRUE)
pred <- read.table("pred.csv", sep=",", header = TRUE)

# change 9999 to NA
followup$Y <- replace(followup$Y, followup$Y == 9999, NA)


# convert visit to data
followup$visit <- as.Date(followup$visit, "%m/%d/%Y")
str(followup)

# ID is now i..ID so change to ID
names(followup)[1]<- "ID"
names(pred)[1] <- "ID"

# b
Merged <- merge(followup, pred, by="ID")

# c
?match()
TheRest <- Merged[duplicated(Merged$ID),]

# first visit dataset
first <- with(Merged, match(1:30, Merged$ID))
FirstVisit <- Merged[first,]


# except the first visit
TheRest <- Merged[duplicated(Merged$ID),]

# last visit
LastVisit <- Merged[!rev(duplicated(rev(Merged$ID))),]



# question 5
# (a)

attitude$complaints[attitude$complaints>80 & attitude$complaints<=100] = "good"
attitude$complaints[attitude$complaints>= 0 & attitude$complaints<=60] = "bad"
attitude$complaints[attitude$complaints>=61 & attitude$complaints<=80] = "okay"

# get mean
with(attitude, tapply(rating, complaints, mean))
